### ISSUE TITLE
Improve CICD non-secret variable configuration to avoid repetition of declarations

### ISSUE THREAD

**Issue by jjgriff93** [UCLH-Foundry/FlowEHR#42]
Adding a new variable, for example `SPARK_VERSION`, to be used by PR and infra-test deployments involves the following process:

- Adding the configuration variable to the GitHub environment
- Then manually setting the variable in the container env block in the `devcontainer_make_command.yml` to reference the GitHub config variable

This is in addition to adding the variable to the `config.yaml` for local use.

We should find a way to reduce this and make it possible for non-secret variables to be set using a single file per environment, which can then be used by whatever caller requires it in both CICD and locally;

My suggestion is using a checked-in `config.yaml` which contains core settings (like `spark_version`), then a file per environment like `config.local.yaml` and `config.infra-test.yaml` that override and set additional variables. 

This will make it easier to modify variables and reduce re-use. Only caveat is for secret variables like ARM_SUBSCRIPTION_ID, this would still need to be set in GitHub secrets, so how we differentiate these in the files between local and GH is a point to consider. We can potentially use a gitignored `.secrets.env` file for local development, then GitHub environment secrets are used in CI. 

## Tasks

- [x] Reference environment yaml files and import into terraform directly (remove `load_env` dependency). ~`tfvar` files might be more suitable~
- [x] Replace naming suffix logic with terraform equivalent / validation
- [x] Remove `LOCAL_MODE` from terragrunt in favour of `tf_in_automation`
- [x] Move core address space / local mode Ip address whitelisting into bootstrap
- [x] Change bootstrapping from bash to terraform so we can get vars directly and validate (suffix, environment etc.)
- [x] Move python random address space to tf bootstrap using `random_integer`?
- [x] Implement suffix_override in tf bootstrap
- [x] Consolidate transform configuration into core config file
- [x] Use yaml input via terragrunt and split out into TF vars? (circumvent global warnings)
- [x] Separate tf versions and providers into common.hcl and use from parent terragrunt and bootstrap
- [x] Strip config out of `devcontainer_make_command` and reference config file
- [x] consolidate GH tokens
- [x] Ability to have core config file and environment-specific that overwrites any values from core (variable precedence)
- [x] Populate environment name to deploy via env var and use to select correct config file(s)
- [x] Restructure apps.yaml config in line with config precedence 
- [x] Don't read data ip each time
- [x] move ci (auth stuff) into the bootstrap folder
- [x] Validate that truncated naming suffix works
- [x] Add clean up TF state and devcontainer step

Notes
- Should `InfraTest` environment references be hard-coded in the actions file? We should try and find a way of populating this dynamically

**Comment by t-young31** [comment]
This definitely warrant further discussion, but just on the `spark_version` aspect: I wonder if it should be hardcoded rather than a variable. Would you ever want the spark version to differ between environments?

**Comment by tanya-borisova** [comment]
> I wonder if it should be hardcoded rather than a variable. Would you ever want the spark version to differ between environments?

The problem is that Spark version needs to be in sync between what's running on the cluster, and what's used for unit tests and local dev workflow

**Comment by t-young31** [comment]
gotcha – thanks, makes lots of sense. so `make test` in pipeline/ would fetch the version from `config.yaml`?

**Comment by tanya-borisova** [comment]
Not quite, it's the devcontainer  build will fetch it. 
(I've typed it and actually realised I haven't implemented this. I will do that as part of my next PR)
