### ISSUE TITLE
Deploy per-app infrastructure

### ISSUE THREAD

**Issue by jjgriff93** [UCLH-Foundry/FlowEHR#64]
Create the code defining the individual app infrastructure (such as deploying individual Apps on an app service, creating a new Cosmos DB collection for state storage, and so on), as well as setting up gold store connectivity, will be defined within the FlowEHR repo (in `/serve`). More info in [design doc](https://github.com/UCLH-Foundry/Book-of-FlowEHR/pull/148/files)

## Acceptance criteria

- `make apps` or similar will deploy all hosting services required for running a sample containerised application with DB connectivity
- There will be no manual sharing of connection strings for the app to consume
- All required app configuration will be available to the container via App Service config injection

## Tasks

- [ ] New repository created within Serve App Container Registry
- [ ] App Service with custom container enabled, with auto-push from ACR registry
- [ ] Cosmos DB database provisioned
- [ ] MSI connectivity to Feature store
- [ ] MSI connectivity to Cosmos DB Database
