### ISSUE TITLE
Scaffold Infrastructure Build

### ISSUE THREAD

**Issue by anastasiakuzn** [UCLH-Foundry/FlowEHR#9]
# Requirements 
- Able to deploy 3x separate deployment units (each with their own state).
- Branch policies for main
- It should be possible to deploy Core, and either the Transform, or the Serving layer independently.
- No TF resources should depend on each other
- There should be a unified way to make all the FlowEHR infrastructure together.
- GitHub Actions with path based trigger to build only the deployment unit that has changed.
- Able to lint and format Terraform on PR
- Able to automate a PR build and pass test if succeeded, destroy after completion.
- Able to deploy to persistent Infra-Test environment

# Proposal 

# Acceptance Criteria

The repository for FlowEHR infrastructure will be created with a consistent structure, and will deploy the required infrastructure for core, transform and serve via makefile commands and Terraform. This deployment will be automated via a GitHub action for PR transient environments and the persistent `Infra-Test` environment.

# Stories/Tasks

- [x] UCLH-Foundry/FlowEHR#8 
- [x] UCLH-Foundry/FlowEHR#7 
- [x] UCLH-Foundry/FlowEHR#6 
- [x] #27 
- [x] #29
